# ./docker-compose.yaml
services:
  postgres:
    image: 'postgres:12'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'

volumes:
  data:
